# Generated by Django 4.2.4 on 2023-11-19 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_products_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='products',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
