# Generated by Django 4.2.4 on 2023-11-19 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_products_created_date_products_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
