# Generated by Django 4.2.4 on 2023-11-19 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
